export * from './main/main.component';
export * from './navbar/navbar.component';
export * from './navbar/navbar.route';
export * from './leftsidebar/leftsidebar.component';
export * from './leftsidebar/leftsidebar.route';
export * from './footer/footer.component';
export * from './footer/footer.route';
export * from './errorpage/errorpage.component';
export * from './errorpage/errorpage.route';